USE ROLE ACCOUNTADMIN;

-- Create the `transform` role
CREATE ROLE IF NOT EXISTS transform;
GRANT ROLE TRANSFORM TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS dbt
  PASSWORD='dbtPassword123'
  LOGIN_NAME='dbt'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE='transform'
  DEFAULT_NAMESPACE='WASEET.RAW'
  COMMENT='DBT user used for data transformation';
GRANT ROLE transform to USER dbt;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS WASEET;
CREATE SCHEMA IF NOT EXISTS WASEET.RAW;

-- Set up permissions to role `transform`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE transform; 
GRANT ALL ON DATABASE WASEET to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE WASEET to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE WASEET to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA WASEET.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA WASEET.RAW to ROLE transform;

-- Ensure Permissions: Make sure the dbt user has the necessary permissions to read this table:
-- GRANT SELECT ON TABLE WASEET.DEV.FULL_MOON_DATES TO ROLE transform;