create or replace task WASEET.DEV.TRAFFIC_REPORT_TASK
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 * * * * UTC'
	as CREATE OR REPLACE VIEW WASEET.DEV.TRAFFIC_REPORT AS
SELECT 
    MAINTAXONOMY,
    maintaxonomytitleenglish,
    DATE_TRUNC('DAY', CREATEDAT) AS CREATEDAT,
    COUNT(DISTINCT ENTITYID) AS Posts,
    SUM(WHATSAPPANDROIDCOUNT) AS WHATSAPPANDROIDCOUNT,
    SUM(WHATSAPPHUAWEICOUNT) AS WHATSAPPHUAWEICOUNT,
    SUM(WHATSAPPIOSCOUNT) AS WHATSAPPIOSCOUNT,
    SUM(WHATSAPPWEBCOUNT) AS WHATSAPPWEBCOUNT,
    SUM(VISITANDROIDCOUNT) AS VISITANDROIDCOUNT,
    SUM(VISITHUAWEICOUNT) AS VISITHUAWEICOUNT,
    SUM(VISITIOSCOUNT) AS VISITIOSCOUNT,
    SUM(VISITWEBCOUNT) AS VISITWEBCOUNT,
    SUM(CALLANDROIDCOUNT) AS CALLANDROIDCOUNT,
    SUM(CALLHUAWEICOUNT) AS CALLHUAWEICOUNT,
    SUM(CALLIOSCOUNT) AS CALLIOSCOUNT,
    SUM(CALLWEBCOUNT) AS CALLWEBCOUNT
FROM WASEET.RAW.CLASSIFIED_LOG_REPORT_ELS 
WHERE updatedat >= DATEADD(MONTH, -2, CURRENT_TIMESTAMP)
  AND ISFREE = TRUE
GROUP BY
    MAINTAXONOMY,
    maintaxonomytitleenglish,
    DATE_TRUNC('DAY', CREATEDAT);